language: python
python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -U -r requirements.txt
  - pip install pytest pytest-cov

script:
  python setup.py develop && pytest --cov; codecov

